### ISSUE TITLE
IndexError with gradient descent

### ISSUE THREAD

**Issue by IsaacWallis** [IsaacWallis/udacity_machine_learning#1]
Traceback (most recent call last):
  File "/Users/ike/Desktop/udacity_machine_learning/capstone/main.py", line 32, in <module>
    best_src_patch, value = gradient_descent.multi_gradient_descent(env_pixels, patch_pixels, patch_indices, 5)
  File "/Users/ike/Desktop/udacity_machine_learning/capstone/gradient_descent.py", line 134, in multi_gradient_descent
    env = Env(env_pixels, patch_pixels, patch_indices)
  File "/Users/ike/Desktop/udacity_machine_learning/capstone/gradient_descent.py", line 18, in __init__
    heatmap_size_x = image.shape[0] - agent_max_x
IndexError: tuple index out of range

**Comment by IsaacWallis** [comment]
FIxed, was problem with scikit image loading, switched to PIL
